packages:
  - apps/*
  - packages/*
  - tooling/*
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': set this to true or false
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  prisma-zod-generator: false
  unrs-resolver: true
  vue-demi: false
