/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
import { customFetch } from "../fetcher";
export type UserFindUniqueReqDtoSelect = {
  id?: boolean;
  email?: boolean;
  name?: boolean;
};

export type UserFindUniqueReqDtoWhere = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  email?: string;
};

export interface UserFindUniqueReqDto {
  select?: UserFindUniqueReqDtoSelect;
  where: UserFindUniqueReqDtoWhere;
}

export interface UserFindUniqueResDtoOutput {
  email?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  name?: string;
}

export type userControllerFindUniqueResponseDefault = {
  data: UserFindUniqueResDtoOutput;
  status: number;
};

export type userControllerFindUniqueResponseError =
  userControllerFindUniqueResponseDefault & {
    headers: Headers;
  };

export type userControllerFindUniqueResponse =
  userControllerFindUniqueResponseError;

export const getUserControllerFindUniqueUrl = () => {
  return `/user/find-unique`;
};

export const userControllerFindUnique = async (
  userFindUniqueReqDto: UserFindUniqueReqDto,
  options?: RequestInit,
): Promise<userControllerFindUniqueResponse> => {
  return customFetch<userControllerFindUniqueResponse>(
    getUserControllerFindUniqueUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userFindUniqueReqDto),
    },
  );
};
