/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/vue-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType,
} from "@tanstack/vue-query";

import { customFetch } from "../fetcher";
export type UserFindUniqueReqDtoSelect = {
  id?: boolean;
  email?: boolean;
  name?: boolean;
};

export type UserFindUniqueReqDtoWhere = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  email?: string;
};

export interface UserFindUniqueReqDto {
  select?: UserFindUniqueReqDtoSelect;
  where: UserFindUniqueReqDtoWhere;
}

export interface UserFindUniqueResDtoOutput {
  email?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  name?: string;
}

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type userControllerFindUniqueResponseDefault = {
  data: UserFindUniqueResDtoOutput;
  status: number;
};

export type userControllerFindUniqueResponseError =
  userControllerFindUniqueResponseDefault & {
    headers: Headers;
  };

export type userControllerFindUniqueResponse =
  userControllerFindUniqueResponseError;

export const getUserControllerFindUniqueUrl = () => {
  return `/user/find-unique`;
};

export const userControllerFindUnique = async (
  userFindUniqueReqDto: UserFindUniqueReqDto,
  options?: RequestInit,
): Promise<userControllerFindUniqueResponse> => {
  return customFetch<userControllerFindUniqueResponse>(
    getUserControllerFindUniqueUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userFindUniqueReqDto),
    },
  );
};

export const getUserControllerFindUniqueMutationOptions = <
  TError = UserFindUniqueResDtoOutput,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerFindUnique>>,
    TError,
    { data: UserFindUniqueReqDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerFindUnique>>,
  TError,
  { data: UserFindUniqueReqDto },
  TContext
> => {
  const mutationKey = ["userControllerFindUnique"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerFindUnique>>,
    { data: UserFindUniqueReqDto }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerFindUnique(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerFindUniqueMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindUnique>>
>;
export type UserControllerFindUniqueMutationBody = UserFindUniqueReqDto;
export type UserControllerFindUniqueMutationError = UserFindUniqueResDtoOutput;

export const useUserControllerFindUnique = <
  TError = UserFindUniqueResDtoOutput,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerFindUnique>>,
      TError,
      { data: UserFindUniqueReqDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof userControllerFindUnique>>,
  TError,
  { data: UserFindUniqueReqDto },
  TContext
> => {
  return useMutation(
    getUserControllerFindUniqueMutationOptions(options),
    queryClient,
  );
};
